CREATE DATABASE InLock_Tarde;

DROP DATABASE InLock_Tarde;

USE InLock_Tarde;

CREATE TABLE TiposUsuarios (
	Id INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR (200),
);


CREATE TABLE Estudios (
	Id INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR (200) NOT NULL
);

CREATE TABLE Jogos (
	Id INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (200) ,
	Descricao VARCHAR (200),
	DataLancamento DATE,
	Valor MONEY,
	EstudioId INT FOREIGN KEY REFERENCES Estudios(Id)
);

CREATE TABLE Usuarios (
	Id INT PRIMARY KEY IDENTITY,
	Email VARCHAR (200),
	Senha VARCHAR (200),
	TipoUsuarioId INT FOREIGN KEY REFERENCES TiposUsuarios(Id)
);


